spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "gotempm-auditsrv"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-requests-cpu: "50m"
        vault.hashicorp.com/agent-inject-secret-timescaledb.txt: "gotempmkv/data/database/timescaledb/auditsrv"
        vault.hashicorp.com/agent-inject-template-timescaledb.txt: |
          {{- with secret "gotempmkv/data/database/timescaledb/auditsrv" -}}
          export DB_CONNECT="postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@{{ .Data.data.server }}/{{ .Data.data.dbname }}?application_name={{ .Data.data.application_name }}"
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-nats.txt: "gotempmkv/data/broker/nats/auditsrv"
        vault.hashicorp.com/agent-inject-template-nats.txt: |
          {{- with secret "gotempmkv/data/broker/nats/auditsrv" -}}
          export MICRO_BROKER_ADDRESS="{{ .Data.data.username }}:{{ .Data.data.password }}@{{ .Data.data.server }}"
          {{- end -}}
    spec:
      serviceAccountName: gotempm-auditsrv
      containers:
        - name: audit
          command: ['sh', '-c', 'source /vault/secrets/timescaledb.txt && source /vault/secrets/nats.txt && ./loader' ]
