apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: nats
  name: nats
spec:
  ports:
  - name: "8222"
    port: 8222
    targetPort: 8222
  - name: "4222"
    port: 4222
    targetPort: 4222
  - name: "6222"
    port: 6222
    targetPort: 6222
  - name: "7777"
    port: 7777
    targetPort: 7777
  selector:
    io.kompose.service: nats
