apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - args:
        - redis-server
        - --requirepass
        - $(REDIS_PASS)
#        - --appendonly
#        - yes
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-secret
        image: redis
        imagePullPolicy: ""
        name: rediscont
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/etc/redis/
          name: redis-config-configmap
      - env:
          - name: REDIS_ADDR
            valueFrom:
              secretKeyRef:
                key: REDIS_ADDR
                name: redisexporter-secret
        image: bitnami/redis-exporter
        imagePullPolicy: ""
        name: redisexporter
        ports:
          - containerPort: 9121
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: redis-config-configmap
        configMap:
          name: redis-config-configmap
