apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: timescaledb
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: timescaledb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: timescaledb
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: timescaledb-secret
        image: bolbeck/gotemp_bbtimescaledb
        imagePullPolicy: ""
        name: timescaledb
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: timescaledb-claim0
      - env:
          - name: DATA_SOURCE_NAME
            valueFrom:
              secretKeyRef:
                key: DATA_SOURCE_NAME
                name: timescaledbexporter-secret
          - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
            valueFrom:
              configMapKeyRef:
                key: PG_EXPORTER_AUTO_DISCOVER_DATABASES
                name: timescaledbexporter-docker-compose-env
        image: bitnami/postgres-exporter
        imagePullPolicy: ""
        name: timescaleexporter
        ports:
          - containerPort: 9187
        resources: { }
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: timescaledb-claim0
        persistentVolumeClaim:
          claimName: timescaledb-claim0
