apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: timescaledb
  name: timescaledb
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  - name: "9187"
    port: 9187
    targetPort: 9187
  selector:
    io.kompose.service: timescaledb
